atime, mtime and ctime setters
zeroos/python-libarchive-c pull request #3
Opened 2016-12-19 11:53 UTC by zeroos

2016-12-19 12:28 UTC, kzuraw requested changes

2016-12-19 12:28 UTC, krzysztofzuraw commented on tests/test_atime_mtime_ctime.py
> +    tree = treestat('libarchive', stat_dict)
Can it be moved to fixture?

2016-12-19 12:28 UTC, krzysztofzuraw commented on tests/test_atime_mtime_ctime.py
> +    tree = treestat('libarchive', stat_dict)
Same here?

2016-12-19 12:28 UTC, krzysztofzuraw commented on tests/test_atime_mtime_ctime.py
> +    atimestamp = 1482144741.495628
can these numbers have more meaning? What does `1482144741.495628` represents? Seconds from 1970?

2016-12-19 12:28 UTC, krzysztofzuraw commented on tests/test_atime_mtime_ctime.py
> +    archive_path = tmpdir.strpath+'/test.zip'
Can it be made using tmpdir interface? http://doc.pytest.org/en/latest/tmpdir.html

2016-12-19 12:28 UTC, krzysztofzuraw commented on tests/test_atime_mtime_ctime.py
> +            for e in archive1:
What is e?

2016-12-19 12:28 UTC, krzysztofzuraw commented on libarchive/entry.py
> +    def _timestamp_sec_nsec(self, timestamp):
what does this function do?

2016-12-19 12:28 UTC, krzysztofzuraw commented on tests/test_atime_mtime_ctime.py
> +def stat_dict(path):
This can be made as a fixture

2016-12-20 11:59 UTC, kzuraw approved these changes
Good job!

2016-12-20 12:07 UTC, merged